# Generated by Django 4.1 on 2022-10-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.user')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField()),
                ('favicon', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('usec', models.DateTimeField()),
                ('page_transition', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handler.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.user')),
            ],
        ),
    ]
