# Generated by Django 4.1 on 2022-10-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0003_remove_entry_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='favicon',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
