# Generated by Django 4.1 on 2022-10-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0004_alter_entry_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
