# Generated by Django 4.1 on 2022-10-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0005_alter_entry_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handler.session'),
        ),
    ]
