# Generated by Django 4.1 on 2022-10-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0006_entry_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_id',
            field=models.BigIntegerField(),
        ),
    ]
