# Generated by Django 4.1 on 2022-10-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.IntegerField(),
        ),
    ]
